#nullable enable
using System;

namespace Cmpnnt.StreamDeckToolkit.Attributes
{
    /// <summary>
    /// Configures action-level manifest properties for a plugin action class.
    /// Controllers (<c>Keypad</c>, <c>Encoder</c>) are derived automatically from the implemented interfaces
    /// and do not need to be specified here.
    /// </summary>
    [AttributeUsage(AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
    public sealed class StreamDeckActionAttribute : Attribute
    {
        /// <summary>Display name of the action shown in Stream Deck. Defaults to the class name.</summary>
        public string? Name { get; set; }

        /// <summary>Tooltip shown when hovering over the action in Stream Deck.</summary>
        public string? Tooltip { get; set; }

        /// <summary>Path to the action icon (without extension). Defaults to <c>"Images/pluginIcon"</c>.</summary>
        public string? Icon { get; set; }

        /// <summary>
        /// Path to the property inspector HTML file. Defaults to <c>"PropertyInspector/{ClassName}.html"</c>,
        /// which matches the file generated by <see cref="SdpiOutputDirectoryAttribute"/>.
        /// </summary>
        public string? PropertyInspectorPath { get; set; }

        /// <summary>URL for the action's support page.</summary>
        public string? SupportURL { get; set; }

        /// <summary>
        /// Whether the action can be used in multi-actions.
        /// When not specified, Stream Deck assumes <c>true</c>.
        /// </summary>
        public bool SupportedInMultiActions { get; set; }

        /// <summary>
        /// Whether the action can be used in key logic actions.
        /// When not specified, Stream Deck assumes <c>true</c>.
        /// </summary>
        public bool SupportedInKeyLogicActions { get; set; }

        /// <summary>
        /// Disables automatic state management for this action.
        /// When not specified, Stream Deck assumes <c>false</c>.
        /// </summary>
        public bool DisableAutomaticStates { get; set; }

        /// <summary>
        /// Disables image caching for this action.
        /// When not specified, Stream Deck assumes <c>false</c>.
        /// </summary>
        public bool DisableCaching { get; set; }

        /// <summary>
        /// Whether the user can set a custom title for this action.
        /// When not specified, Stream Deck assumes <c>true</c>.
        /// </summary>
        public bool UserTitleEnabled { get; set; }

        /// <summary>
        /// Whether the action appears in the Stream Deck action list.
        /// When not specified, Stream Deck assumes <c>true</c>.
        /// </summary>
        public bool VisibleInActionsList { get; set; }
    }
}
