using System.Collections.Generic;
using System.Text;

namespace Cmpnnt.StreamDeckToolkit.SourceGenerators.Templates;

internal static class ManifestProviderTemplate
{
    public static string Generate(ManifestGeneratorInput input)
    {
        var (msbuild, pluginAttr, actions, configClassName) = input;

        string assemblyNameLower = (msbuild.AssemblyName ?? "plugin").ToLowerInvariant();

        // Resolve plugin-level values: attribute > MSBuild > convention
        string pluginUuid = pluginAttr?.Uuid ?? assemblyNameLower;
        string pluginName = pluginAttr?.Name ?? msbuild.AssemblyName ?? "Plugin";
        string author = msbuild.Authors ?? string.Empty;
        string version = msbuild.Version ?? "1.0.0";
        string description = msbuild.Description ?? string.Empty;
        string icon = pluginAttr?.Icon ?? "Images/pluginIcon";
        string? category = pluginAttr?.Category;
        string? categoryIcon = pluginAttr?.CategoryIcon;
        string? url = pluginAttr?.Url ?? msbuild.PackageProjectUrl;
        string? supportUrl = pluginAttr?.SupportUrl;
        int sdkVersion = pluginAttr?.SdkVersion ?? 2;
        string softwareMin = pluginAttr?.SoftwareMinVersion ?? "6.4";
        string? windowsMin = pluginAttr?.WindowsMinVersion;
        string? macMin = pluginAttr?.MacMinVersion;
        string codePath = pluginAttr?.CodePathWin ?? $"{assemblyNameLower}.exe";
        string? codePathMac = pluginAttr?.CodePathMac;
        string? globalPropertyInspectorPath = pluginAttr?.PropertyInspectorPath;

        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// DO NOT MODIFY");
        sb.AppendLine();
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using Cmpnnt.StreamDeckToolkit.Manifest;");
        sb.AppendLine();
        sb.AppendLine("namespace GeneratedManifest");
        sb.AppendLine("{");
        sb.AppendLine("    internal static class ManifestProvider");
        sb.AppendLine("    {");
        sb.AppendLine("        public static ManifestRoot GetManifestData()");
        sb.AppendLine("        {");

        if (configClassName != null)
            sb.AppendLine($"            var userConfig = new {configClassName}();");

        sb.AppendLine("            var root = new ManifestRoot();");
        sb.AppendLine($"            root.Name = {Q(pluginName)};");
        sb.AppendLine($"            root.Author = {Q(author)};");
        sb.AppendLine($"            root.Version = {Q(version)};");
        sb.AppendLine($"            root.Description = {Q(description)};");
        sb.AppendLine($"            root.Icon = {Q(icon)};");
        sb.AppendLine($"            root.UUID = {Q(pluginUuid)};");
        sb.AppendLine($"            root.CodePath = {Q(codePath)};");
        sb.AppendLine($"            root.SDKVersion = {sdkVersion};");
        sb.AppendLine($"            root.Software = new ManifestSoftware {{ MinimumVersion = {Q(softwareMin)} }};");

        if (category != null)
            sb.AppendLine($"            root.Category = {Q(category)};");
        if (categoryIcon != null)
            sb.AppendLine($"            root.CategoryIcon = {Q(categoryIcon)};");
        if (url != null)
            sb.AppendLine($"            root.URL = {Q(url)};");
        if (supportUrl != null)
            sb.AppendLine($"            root.SupportURL = {Q(supportUrl)};");
        if (codePathMac != null)
            sb.AppendLine($"            root.CodePathMac = {Q(codePathMac)};");
        if (globalPropertyInspectorPath != null)
            sb.AppendLine($"            root.PropertyInspectorPath = {Q(globalPropertyInspectorPath)};");

        // OS list
        sb.AppendLine("            root.OS = new List<ManifestOS>");
        sb.AppendLine("            {");
        if (windowsMin != null)
            sb.AppendLine($"                new ManifestOS {{ Platform = \"windows\", MinimumVersion = {Q(windowsMin)} }},");
        if (macMin != null)
            sb.AppendLine($"                new ManifestOS {{ Platform = \"mac\", MinimumVersion = {Q(macMin)} }},");
        if (windowsMin == null && macMin == null) // Default: Windows 10
            sb.AppendLine("                new ManifestOS { Platform = \"windows\", MinimumVersion = \"10\" },");
        sb.AppendLine("            };");

        // POCO overrides
        if (configClassName != null)
        {
            sb.AppendLine("            if (userConfig.ApplicationsToMonitor != null)");
            sb.AppendLine("                root.ApplicationsToMonitor = userConfig.ApplicationsToMonitor;");
            sb.AppendLine("            if (userConfig.Profiles != null && userConfig.Profiles.Length > 0)");
            sb.AppendLine("                root.Profiles = new List<ManifestProfile>(userConfig.Profiles);");
        }

        // Actions
        sb.AppendLine("            root.Actions = new List<ManifestAction>();");

        foreach (ActionInfo action in actions)
        {
            ActionAttrData? attr = action.AttrData;
            string actionName = attr?.Name ?? action.ClassName;
            string actionIcon = attr?.Icon ?? "Images/pluginIcon";
            string propertyInspectorPath = attr?.PropertyInspectorPath
                ?? globalPropertyInspectorPath
                ?? $"PropertyInspector/{action.ClassName}.html";

            sb.AppendLine("            {");
            sb.AppendLine("                var action = new ManifestAction();");
            sb.AppendLine($"                action.UUID = {Q(action.ActionUuid)};");
            sb.AppendLine($"                action.Name = {Q(actionName)};");
            sb.AppendLine($"                action.Icon = {Q(actionIcon)};");
            sb.AppendLine($"                action.PropertyInspectorPath = {Q(propertyInspectorPath)};");

            // Controllers derived from interfaces
            var controllers = new List<string>();
            if (action.IsKeypad) controllers.Add("\"Keypad\"");
            if (action.IsEncoder) controllers.Add("\"Encoder\"");
            if (controllers.Count > 0)
                sb.AppendLine($"                action.Controllers = [{string.Join(", ", controllers)}];");

            // Optional attribute-controlled booleans (only emitted when explicitly set)
            if (attr?.SupportedInMultiActions != null)
                sb.AppendLine($"                action.SupportedInMultiActions = {B(attr.SupportedInMultiActions.Value)};");
            if (attr?.SupportedInKeyLogicActions != null)
                sb.AppendLine($"                action.SupportedInKeyLogicActions = {B(attr.SupportedInKeyLogicActions.Value)};");
            if (attr?.DisableAutomaticStates != null)
                sb.AppendLine($"                action.DisableAutomaticStates = {B(attr.DisableAutomaticStates.Value)};");
            if (attr?.DisableCaching != null)
                sb.AppendLine($"                action.DisableCaching = {B(attr.DisableCaching.Value)};");
            if (attr?.UserTitleEnabled != null)
                sb.AppendLine($"                action.UserTitleEnabled = {B(attr.UserTitleEnabled.Value)};");
            if (attr?.VisibleInActionsList != null)
                sb.AppendLine($"                action.VisibleInActionsList = {B(attr.VisibleInActionsList.Value)};");
            if (attr?.Tooltip != null)
                sb.AppendLine($"                action.Tooltip = {Q(attr.Tooltip)};");
            if (attr?.SupportUrl != null)
                sb.AppendLine($"                action.SupportURL = {Q(attr.SupportUrl)};");

            // States from POCO defaulting to a single image state
            if (configClassName != null)
            {
                sb.AppendLine("                action.States = userConfig.DefaultStates != null");
                sb.AppendLine("                    ? [..userConfig.DefaultStates]");
                sb.AppendLine("                    : [new ManifestStateConfig { Image = \"Images/pluginAction\" }];");

                if (action.IsEncoder)
                    sb.AppendLine("                action.Encoder = userConfig.DefaultEncoder;");
            }
            else
            {
                sb.AppendLine("                action.States = [new ManifestStateConfig { Image = \"Images/pluginAction\" }];");
            }

            sb.AppendLine("                root.Actions.Add(action);");
            sb.AppendLine("            }");
        }

        sb.AppendLine("            return root;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static string Q(string s) => $"\"{Escape(s)}\"";
    private static string B(bool b) => b ? "true" : "false";
    private static string Escape(string s) => s.Replace("\\", "\\\\").Replace("\"", "\\\"");
}
